Repository grafana/scenes, pull requests merged in 2023-11, with the labels that each got.

#410 Variables: Multi select batch update
  packages/scenes-app/src/demos/variables.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
Labels: minor

#444 VizPanel: Fixes series visibility toggling
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: release

#445 PanelContext: Eventbus should not filter out local events
  packages/scenes-app/src/demos/cursorSync.tsx
  packages/scenes/src/behaviors/CursorSync.ts
Labels: release

#454 SceneQueryRunner: Handle alert states data layer
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/core/types.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/layers/TestDataLayer.ts
  packages/scenes/src/querying/layers/annotations/filterAnnotations.test.ts
  packages/scenes/src/querying/layers/annotations/filterAnnotations.ts
  packages/scenes/src/querying/layers/annotations/filterAnnotationsOperator.ts
Labels: minor, release

#455 Variables: Fixes url sync issue for key/value multi value variables
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: release

#459 Variables: Add natural sort from core grafana to query variables
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  packages/scenes/src/variables/variants/query/utils.ts
Labels: minor, area/variables

#469 Adhoc filters: Add tagKeyRegexFilter prop
  packages/scenes/src/variables/adhoc/AdHocFiltersSet.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersSet.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: release

#472 Variables: Add type guards for variables
  packages/scenes/src/index.ts
  packages/scenes/src/variables/variants/guards.ts
Labels: minor, release

#474 Fix non-null assertion in SceneQueryRunner
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: patch, release

#476 Variables: Clear error state
  packages/scenes/src/variables/variants/DataSourceVariable.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: patch, release

#478 VizPanelRenderer: Round visualization width pushed to data provider
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: type/bug, patch, release

#481 SceneQueryRunner: Fixes issue with waiting for variables
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: release

#483 VizPanelMenu: Fix auto focus / keyboard navigation issue
  packages/scenes/src/components/VizPanel/VizPanelMenu.tsx
Labels: patch
