Repository grafana/scenes, pull requests merged in 2023-06, with the labels that each got.

#222 TimeRangePicker: Default to the "isOnCanvas" true look
  packages/scenes/src/components/SceneRefreshPicker.tsx
  packages/scenes/src/components/SceneTimePicker.tsx
Labels: minor

#221 SceneQueryRunner: Re-run queries onActivate when time range changed
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: minor

#223 SceneQueryRunner: Only use containerWidth when maxDataPointsFromWidth is true
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: minor, release

#224 Docs: Unify admonition styles
  docusaurus/docs/advanced-activation-handlers.md
  docusaurus/docs/advanced-data.md
  docusaurus/docs/advanced-variables.md
  docusaurus/docs/core-concepts.md
  docusaurus/docs/getting-started.md
  docusaurus/docs/scene-app-drilldown.md
  docusaurus/docs/scene-app.md
  docusaurus/docs/transformations.md
Labels: documentation, no-changelog

#228 SceneAppPage: Fix page with tabs and drilldown on main page level
  packages/scenes/src/components/SceneApp/SceneApp.test.tsx
  packages/scenes/src/components/SceneApp/SceneAppPage.tsx
Labels: minor, release

#231 Demos app Readme update
  packages/scenes-app/README.md
Labels: no-changelog

#225 PanelBuilders: Typed API for VizPanel creation
  docusaurus/docs/visualizations.md
  lerna.json
  packages/scenes-app/src/demos/flexLayout.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/core/PanelBuilders/FieldConfigOverridesBuilder.ts
  packages/scenes/src/core/PanelBuilders/StandardFieldConfigBuilders.ts
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
  packages/scenes/src/core/PanelBuilders/__snapshots__/VizPanelBuilder.test.ts.snap
  packages/scenes/src/core/PanelBuilders/index.ts
  packages/scenes/src/core/PanelBuilders/types.ts
  packages/scenes/src/index.ts
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  yarn.lock
Labels: enhancement, minor, release

#220 VizPanel: Allow queries to be cancelled
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/queryCancellation.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/core/types.ts
  packages/scenes/src/querying/SceneDataTransformer.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: enhancement, minor, release

#229 SplitLayout: Add Splitter and SplitLayout
  docusaurus/docs/scene-layout.md
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/split.tsx
  packages/scenes-app/src/demos/withDrilldown/scenes.tsx
  packages/scenes/src/components/layout/split/SplitLayout.ts
  packages/scenes/src/components/layout/split/SplitLayoutRenderer.tsx
  packages/scenes/src/components/layout/split/Splitter.tsx
  packages/scenes/src/index.ts
Labels: enhancement

#235 PanelBuilders: Add method for setting behaviors
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
Labels: patch, release

#236 Documentation: Review
  docusaurus/docs/advanced-activation-handlers.md
  docusaurus/docs/advanced-activation-handlers.tsx
  docusaurus/docs/advanced-custom-scene-objects.md
  docusaurus/docs/advanced-custom-scene-objects.tsx
  docusaurus/docs/advanced-data.md
  docusaurus/docs/advanced-data.tsx
  docusaurus/docs/advanced-variables.md
  docusaurus/docs/advanced-variables.tsx
  docusaurus/docs/core-concepts.md
  docusaurus/docs/core-concepts.tsx
  docusaurus/docs/getting-started.md
  docusaurus/docs/getting-started.tsx
  docusaurus/docs/scene-app-drilldown.md
  docusaurus/docs/scene-app-tabs.md
  docusaurus/docs/scene-app.md
  docusaurus/docs/scene-layout.md
  docusaurus/docs/scene-layout.tsx
  docusaurus/docs/transformations.md
  docusaurus/docs/transformations.tsx
  docusaurus/docs/variables.md
  docusaurus/docs/variables.tsx
  docusaurus/docs/visualizations.md
  docusaurus/docs/visualizations.tsx
  packages/scenes-app/.config/tsconfig.json
  packages/scenes-app/src/demos/behaviors/behaviorsDemo.tsx
  packages/scenes-app/src/demos/docs-examples.tsx
  packages/scenes-app/src/demos/dynamicPage.tsx
  packages/scenes-app/src/demos/flexLayout.tsx
  packages/scenes-app/src/demos/grid.tsx
  packages/scenes-app/src/demos/gridWithRow.tsx
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/lazyLoad.tsx
  packages/scenes-app/src/demos/nestedScene.tsx
  packages/scenes-app/src/demos/panelContext.tsx
  packages/scenes-app/src/demos/panelMenu.ts
  packages/scenes-app/src/demos/panelRepeater.tsx
  packages/scenes-app/src/demos/queryEditor.tsx
  packages/scenes-app/src/demos/responsiveLayout.tsx
  packages/scenes-app/src/demos/split.tsx
  packages/scenes-app/src/demos/timeZones.tsx
  packages/scenes-app/src/demos/utils.ts
  packages/scenes-app/src/demos/variables.tsx
  packages/scenes-app/src/demos/withDrilldown/panels.tsx
  packages/scenes-app/src/demos/withDrilldown/scenes.tsx
  packages/scenes/src/core/SceneTimeRange.test.tsx
Labels: documentation, no-changelog

#237 Docs: General copy edit of Visualizations
  docusaurus/docs/visualizations.md
Labels: documentation, no-changelog

#238 SceneQueryRunner: Cancel previous request when starting new one
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: bug, patch, release

#240 Readme: Remove feature toggle requirement
  packages/scenes/README.md
Labels: no-changelog
