Repository grafana/scenes, pull requests merged in 2023-07, with the labels that each got.

#241 SceneGridRow: Fix rows auto collapsing on load due to url sync
  packages/scenes/src/components/layout/grid/SceneGridRow.tsx
Labels: patch

#159 Querying: Support runtime registered data source
  docusaurus/docs/advanced-custom-datasource.md
  docusaurus/website/docusaurus.config.js
  docusaurus/website/sidebars.js
  packages/scenes-app/src/demos/flexLayout.tsx
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/runtimeDataSourceDemo.tsx
  packages/scenes/src/components/layout/split/SplitLayoutRenderer.tsx
  packages/scenes/src/index.ts
  packages/scenes/src/querying/RuntimeDataSource.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/utils/getDataSource.ts
  packages/scenes/src/variables/interpolation/formatRegistry.ts
Labels: minor

#243 SceneGridLayout: Fixes issues with unmount on every re-render
  packages/scenes-app/src/demos/lazyLoad.tsx
  packages/scenes/src/components/layout/grid/LazyLoader.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: minor

#251 SceneGridItem: Makes isDraggable and isResizable optional
  packages/scenes/src/components/layout/grid/types.ts
  packages/scenes/src/core/types.ts
Labels: minor

#253 SceneQueryRunner: Provide rangeRaw in request
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: minor, release

#264 PanelBuilders: Fix regex matcher for overrides
  packages/scenes/src/core/PanelBuilders/FieldConfigOverridesBuilder.ts
Labels: bug, patch

#267 FieldConfigOverridesBuilder: Simplify matchFieldsByValue API
  packages/scenes/src/core/PanelBuilders/FieldConfigOverridesBuilder.ts
Labels: minor, release

#268 Mark grafana dependencies as peerDependencies
  packages/scenes-app/package.json
  packages/scenes-app/src/pages/DemoListPage.tsx
  packages/scenes/package.json
  packages/scenes/src/components/NestedScene.tsx
  yarn.lock
Labels: minor, release

#259 Behaviors: Provide behavior for visualization cursor sync
  packages/scenes-app/src/demos/cursorSync.tsx
  packages/scenes-app/src/demos/index.ts
  packages/scenes/src/behaviors/CursorSync.ts
  packages/scenes/src/behaviors/index.ts
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/core/SceneObjectBase.tsx
Labels: minor, release

#248 Tabs: Add icon and suffix
  packages/scenes-app/src/demos/withDrilldown/WithDrilldown.tsx
  packages/scenes/src/components/SceneApp/SceneApp.test.tsx
  packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
  packages/scenes/src/components/SceneApp/types.ts
Labels: minor, release

#257 Docs: Grammar and style edits
  docusaurus/docs/advanced-custom-datasource.md
Labels: type/documentation, no-changelog
