Repository grafana/scenes, pull requests merged in 2023-03, with the labels that each got.

#37 Add support for TextBoxVariable
  src/index.ts
  src/variables/components/VariableValueInput.tsx
  src/variables/variants/TextBoxVariable.tsx
Labels: enhancement

#36 Implement auto-refresh for scene time range
  package.json
  src/components/SceneRefreshPicker.test.ts
  src/components/SceneRefreshPicker.tsx
  src/components/SceneTimePicker.tsx
  src/index.ts
Labels: enhancement

#85 Auto: Automate changelog and github releases
  .github/workflows/build-and-test.yml
  .github/workflows/publish-npm.yml
  .gitignore
  package.json
  yarn.lock
Labels: patch, release

#88 Update
  CHANGELOG.md
Labels: release

#89 Auto: Testing
  CHANGELOG.md
  lerna.json
  package.json
  packages/scenes-app/package.json
  packages/scenes/package.json
Labels: patch, release

#90 Release: test
  packages/scenes-app/package.json
Labels: release

#91 Auto release test
  yarn.lock
Labels: release

#92 Auto: Another release test
  .github/workflows/node-ci.yml
  package.json
  packages/scenes-app/package.json
  packages/scenes/package.json
  yarn.lock
Labels: patch, release

#106 release test
  packages/scenes/src/variables/interpolation/sceneInterpolator.ts
Labels: patch, release

#100 UrlSync: Simplify url sync interface
  packages/scenes/src/components/layout/SceneGridRow.tsx
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/core/types.ts
  packages/scenes/src/services/SceneObjectUrlSyncConfig.ts
  packages/scenes/src/services/UrlSyncManager.test.ts
  packages/scenes/src/services/UrlSyncManager.ts
  packages/scenes/src/variables/macros/UrlTimeRangeMacro.ts
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
  packages/scenes/src/variables/variants/TextBoxVariable.tsx
Labels: minor, release

#110 Skip PRs with label
  .autorc
  package.json
  packages/scenes/src/core/SceneTimeRange.test.tsx
  yarn.lock
Labels: no-changelog

#112 Interpolation: FormatRegistryID is now replaced by VariableFormatID from schema package
  packages/scenes/src/index.ts
  packages/scenes/src/variables/interpolation/formatRegistry.test.ts
  packages/scenes/src/variables/interpolation/formatRegistry.ts
  packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts
  packages/scenes/src/variables/interpolation/sceneInterpolator.ts
  packages/scenes/src/variables/macros/AllVariablesMacro.ts
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
  yarn.lock
Labels: minor

#97 Layout: Create atomic, layout specific objects
  packages/scenes-app/src/pages/Demos/Demos.tsx
  packages/scenes-app/src/pages/Demos/getDemos.ts
  packages/scenes-app/src/pages/Demos/scenes/flexLayout.tsx
  packages/scenes-app/src/pages/Demos/scenes/grid.tsx
  packages/scenes-app/src/pages/Demos/scenes/gridWithRow.tsx
  packages/scenes-app/src/pages/Demos/scenes/nestedScene.tsx
  packages/scenes-app/src/pages/Demos/scenes/panelMenu.ts
  packages/scenes-app/src/pages/Demos/scenes/panelRepeater.tsx
  packages/scenes-app/src/pages/Home/scenes.tsx
  packages/scenes-app/src/pages/WithDrilldown/WithDrilldown.tsx
  packages/scenes-app/src/pages/WithDrilldown/panels.tsx
  packages/scenes-app/src/pages/WithDrilldown/scenes.tsx
  packages/scenes/src/components/NestedScene.test.tsx
  packages/scenes/src/components/NestedScene.tsx
  packages/scenes/src/components/SceneApp/SceneApp.test.tsx
  packages/scenes/src/components/SceneReactObject.test.tsx
  packages/scenes/src/components/SceneRefreshPicker.test.ts
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/components/layout/SceneFlexLayout.tsx
  packages/scenes/src/components/layout/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
  packages/scenes/src/components/layout/grid/SceneGridRow.tsx
  packages/scenes/src/components/layout/grid/constants.ts
  packages/scenes/src/components/layout/grid/types.ts
  packages/scenes/src/core/types.ts
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneDataTransformer.test.ts
  packages/scenes/src/services/UrlSyncManager.test.ts
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
Labels: minor, release

#115 App: Show errors in the landing page if system is not configured properly
  packages/scenes-app/provisioning/datasources/default.yaml
  packages/scenes-app/src/constants.ts
  packages/scenes-app/src/pages/Home/Home.tsx
Labels: no-changelog

#114 SceneObject: Change how activate works and remove deactivate
  packages/scenes/.eslintrc
  packages/scenes/src/components/SceneRefreshPicker.test.ts
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/core/SceneComponentWrapper.tsx
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/core/types.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/services/UrlSyncManager.test.ts
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: minor
