Repository grafana/scenes, pull requests merged in 2023-08, with the labels that each got.

#273 Bump grafana dependencies
  .github/workflows/node-ci.yml
  packages/scenes-app/package.json
  packages/scenes/package.json
  packages/scenes/src/components/SceneApp/SceneApp.test.tsx
  yarn.lock
Labels: dependencies

#276 Adding developer portal dev workflow and config
  .github/workflows/deploy-to-dev-portal-dev.yml
  docusaurus/website/docusaurus.config.devportal.js
Labels: type/documentation

#278 Fixing paths
  .github/workflows/deploy-to-dev-portal-prod.yml
Labels: type/documentation, no-changelog

#279 Website: Update theme for developer portal
  docusaurus/docs/core-concepts.md
  docusaurus/website/docusaurus.config.devportal.js
  docusaurus/website/docusaurus.config.devportal.prod.js
  docusaurus/website/docusaurus.config.js
  docusaurus/website/package.json
  docusaurus/website/src/components/HomepageFeatures/index.tsx
  docusaurus/website/src/components/HomepageFeatures/styles.module.css
  docusaurus/website/src/components/HomepageGettingStarted/index.tsx
  docusaurus/website/src/css/custom.css
  docusaurus/website/src/css/theme.css
  docusaurus/website/src/pages/homepage_logo.svg
  docusaurus/website/src/pages/index.module.css
  docusaurus/website/src/pages/index.tsx
  docusaurus/website/src/theme/DocSidebar/Desktop/CollapseButton/index.tsx
  docusaurus/website/src/theme/DocSidebar/Desktop/CollapseButton/styles.module.css
  docusaurus/website/src/theme/DocSidebar/Desktop/Content/index.tsx
  docusaurus/website/src/theme/DocSidebar/Desktop/Content/styles.module.css
  docusaurus/website/src/theme/DocSidebar/Desktop/index.tsx
  docusaurus/website/src/theme/DocSidebar/Desktop/styles.module.css
  docusaurus/website/src/theme/DocSidebar/Mobile/index.tsx
  docusaurus/website/src/theme/DocSidebar/index.tsx
  docusaurus/website/src/theme/prism.js
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa0ZL7SUc.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1pL7SUc.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa25L7SUc.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2JL7SUc.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2ZL7SUc.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7SUc.woff2
  docusaurus/website/static/font/roboto/L0xTDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vrtSM1J-gEPT5Ese6hmHSh0mQ.woff2
  docusaurus/website/static/img/hero_banner.png
  docusaurus/website/static/img/sceneTree.png
  yarn.lock
Labels: type/documentation, no-changelog

#285 VariableValueSelectors: Don't wrap labels
  packages/scenes/src/variables/components/VariableValueSelectors.tsx
Labels: type/bug, patch

#287 VizPanel: Handle plugin not found scenario correctly
  packages/scenes-app/src/demos/flexLayout.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: type/bug, patch

#261 Allow template variables to be cancelled
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
  packages/scenes/src/variables/variants/TestVariable.tsx
Labels: type/enhancement, area/variables

#288 SceneQueryRunner: Fixes issues when being cloned
  packages/scenes/src/components/layout/grid/SceneGridItem.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: minor, release

#297 sceneUtils: cloneSceneObjectState
  packages/scenes/src/core/sceneGraph/utils.ts
  packages/scenes/src/index.ts
Labels: minor, release

#244 Scene: Allow time range comparison
  docusaurus/docs/advanced-time-range-comparison.md
  docusaurus/docs/advanced-time-range-comparison.tsx
  docusaurus/website/sidebars.js
  packages/scenes-app/src/demos/docs-examples.tsx
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/timeRangeComparison.tsx
  packages/scenes/src/components/SceneApp/types.ts
  packages/scenes/src/components/SceneTimeRangeCompare.test.ts
  packages/scenes/src/components/SceneTimeRangeCompare.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/core/PanelBuilders/FieldConfigOverridesBuilder.ts
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/timeShiftQueryResponseOperator.ts
  packages/scenes/src/utils/getCompareSeriesRefId.ts
Labels: minor, release

#300 Website: Add search and links to dev portal home
  docusaurus/website/README.md
  docusaurus/website/docusaurus.config.devportal.js
  docusaurus/website/docusaurus.config.devportal.prod.js
  docusaurus/website/package.json
  docusaurus/website/src/css/custom.css
  yarn.lock
Labels: type/documentation, no-changelog

#307 Docs: Override matchers
  docusaurus/docs/visualizations.md
Labels: type/documentation, no-changelog

#304 SceneObjectRef: Provide a way to have references to other scene objects without impacting parent
  docusaurus/docs/core-concepts.md
  packages/scenes/src/core/SceneObjectRef.test.ts
  packages/scenes/src/core/SceneObjectRef.ts
  packages/scenes/src/core/sceneGraph/utils.ts
  packages/scenes/src/index.ts
Labels: minor, release

#308 SceneGridLayout: Remove z-index
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: patch, release

#302 VizPanel: Allow panels to rendered without layout parent
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
Labels: minor
