Repository grafana/scenes, pull requests merged in 2023-09, with the labels that each got.

#310 VizPanel: Set key on time range header item
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: no-changelog

#312 SceneTimeRangeTransformerBase
  packages/scenes/src/core/SceneTimeRangeTransformerBase.tsx
  packages/scenes/src/core/SceneTimeZoneOverride.tsx
  packages/scenes/src/index.ts
  packages/scenes/src/utils/utils.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: minor, release

#316 QueryVariable: Support null ds
  packages/scenes/src/utils/getDataSource.ts
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: minor

#315 VizPanel: Remove left-over isDraggable/isResizable state
  packages/scenes-app/src/demos/grid.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
Labels: minor

#317 Variables: New LocalValueVariable to better support repeating panels
  packages/scenes/src/index.ts
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
  packages/scenes/src/variables/types.ts
  packages/scenes/src/variables/variants/LocalValueVariable.ts
Labels: minor

#314 TestVariable: Add optionsToReturn and other unrelated changes
  packages/scenes/src/components/SceneDebugger/SceneDebugger.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
  packages/scenes/src/components/layout/grid/types.ts
  packages/scenes/src/index.ts
  packages/scenes/src/variables/variants/ConstantVariable.ts
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
  packages/scenes/src/variables/variants/TestVariable.tsx
Labels: minor, release

#321 SceneGridRow: Small design change and fixes, add actions support
  packages/scenes/src/components/SceneDragHandle.tsx
  packages/scenes/src/components/layout/grid/SceneGridRow.tsx
Labels: release

#323 Scenes 1.0 release prep
  README.md
  docusaurus/website/src/pages/index.tsx
  packages/scenes/README.md
Labels: major, release

#327 License: Switch to Apache 2.0
  LICENSE
  package.json
Labels: minor, release

#326 SceneGridLayout: Fix toggle row issue
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
  packages/scenes/src/components/layout/grid/SceneGridRow.tsx
Labels: patch, release

#332 SceneControlsSpacer: Fix flickering
  packages/scenes/src/components/SceneControlsSpacer.tsx
Labels: patch, release

#335 NestedScene: Update design to match grid row, add controls property and update demo scene to include variables
  package.json
  packages/scenes-app/src/demos/nestedScene.tsx
  packages/scenes-app/src/demos/utils.ts
  packages/scenes-app/src/demos/variables.tsx
  packages/scenes/src/components/NestedScene.tsx
  packages/scenes/src/components/layout/grid/SceneGridRow.tsx
Labels: minor, release

#342 AnnotationsDataLayer: Handle data source error
  packages/scenes/src/querying/layers/SceneDataLayerControls.tsx
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts
  packages/scenes/src/utils/ControlsLabel.tsx
  packages/scenes/src/utils/getMessageFromError.ts
Labels: patch, release

#343 Annotations filtering operator: Correctly populate filtered frames
  packages/scenes/src/querying/layers/annotations/filterAnnotationsOperator.test.ts
  packages/scenes/src/querying/layers/annotations/filterAnnotationsOperator.ts
Labels: patch, release

#344 Data layer controls: Allow hiding
  packages/scenes/src/core/types.ts
  packages/scenes/src/querying/layers/SceneDataLayerControls.tsx
Labels: patch

#345 SceneAppPage: Fix infinite recurision of enrichDataRequest
  packages/scenes/src/components/SceneApp/SceneAppPage.test.tsx
  packages/scenes/src/components/SceneApp/SceneAppPage.tsx
Labels: patch, release

#348 Variables: Fixes issue with running variable queries with custom or legacy runner
  packages/scenes/src/variables/variants/query/createQueryVariableRunner.ts
Labels: minor, release

#350 Variables: Fix issue with previous fix
  packages/scenes/src/variables/variants/query/createQueryVariableRunner.ts
Labels: minor, release

#347 AnnotationsDataLayer: Provide inheritance extension points
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts
  packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts
Labels: patch, release

#351 AnnotationsDataLayer: Events deduplication
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts
  packages/scenes/src/querying/layers/annotations/utils.ts
Labels: patch, release

#354 SceneDataTransformer: Handle transformation errors
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/transformations.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/querying/SceneDataTransformer.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: patch, release

#357 SceneApp: Introduce a useSceneApp hook that should replace useMemo as method of caching SceneApp instance
  docusaurus/docs/scene-app.md
  packages/scenes-app/src/pages/DemoListPage.tsx
  packages/scenes/src/components/SceneApp/SceneApp.test.tsx
  packages/scenes/src/components/SceneApp/SceneApp.tsx
  packages/scenes/src/index.ts
Labels: release

#358 AnnotationsDataLayer: Add variables support
  packages/scenes/src/core/types.ts
  packages/scenes/src/querying/layers/SceneDataLayerBase.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts
  packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts
  packages/scenes/src/variables/VariableDependencyConfig.ts
  packages/scenes/src/variables/VariableValueRecorder.ts
Labels: minor, release

#360 SceneTimeRangeCompare: Enable URL sync
  packages/scenes/src/components/SceneTimeRangeCompare.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/core/SceneTimeZoneOverride.tsx
  packages/scenes/src/utils/evaluateTimeRange.ts
  packages/scenes/src/utils/parseUrlParam.test.ts
  packages/scenes/src/utils/parseUrlParam.ts
Labels: minor, release

#364 AnnotationsDataLayer: Support query request enriching
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/getEnrichedDataRequest.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts
  packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts
  packages/scenes/src/utils/test/TestSceneWithRequestEnricher.ts
Labels: patch, release

#363 VizPanel: Allow options and field config updates
  packages/scenes-app/src/demos/dynamicPanelOptions.tsx
  packages/scenes-app/src/demos/index.ts
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/core/PanelBuilders/FieldConfigBuilder.ts
  packages/scenes/src/core/PanelBuilders/FieldConfigBuilders.ts
  packages/scenes/src/core/PanelBuilders/PanelOptionsBuilder.ts
  packages/scenes/src/core/PanelBuilders/PanelOptionsBuilders.ts
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
  packages/scenes/src/core/PanelBuilders/index.ts
  packages/scenes/src/index.ts
Labels: minor, release

#369 Demos: Fix panel repeater demo
  packages/scenes-app/src/demos/panelRepeater.tsx
Labels: patch, release

#370 Demos: Client side data filtering
  packages/scenes-app/src/demos/filteringData.tsx
  packages/scenes-app/src/demos/index.ts
Labels: no-changelog

#371 SceneVariableSet: Show and log errors
  packages/scenes/src/variables/components/VariableValueSelectors.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
  packages/scenes/src/variables/variants/TestVariable.tsx
Labels: minor

#375 SceneTimeRange: Add weekStart support and make sure fiscalYearMonth is used everywhere
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/core/SceneTimeZoneOverride.tsx
  packages/scenes/src/core/types.ts
Labels: patch, release

#376 Variables: Support skipUrlSync option
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: minor
