Repository grafana/scenes, pull requests merged in 2023-12, with the labels that each got.

#488 Simplify interval macro
  packages/scenes/src/core/types.ts
  packages/scenes/src/querying/SceneDataTransformer.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/variables/macros/timeMacros.ts
Labels: patch

#489 Variables: Query - Add optional `definition` prop to state
  packages/scenes-app/src/demos/variables.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: minor, release, area/variables

#490 QueryVariable: Run query with scene time range on when configured to run on load
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: patch

#491 VizPanel: Expose events for interactions
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/core/events.ts
Labels: minor, release

#501 Variables: Fixes issue with chained variable and cascading updates
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
Labels: type/bug, patch, release

#508 IntervalVariable: Makes it return the original variable expression when data or request is not present
  packages/scenes/src/variables/macros/timeMacros.test.ts
  packages/scenes/src/variables/macros/timeMacros.ts
Labels: release

#498 Splitter: Fixes small issue with keyboard control
  packages/scenes/src/components/layout/split/Splitter.tsx
Labels: type/bug
