Repository grafana/scenes, pull requests merged in 2023-04, with the labels that each got.

#118 SceneObject: Add forEachChild to SceneObject interface and SceneObjectBase
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/core/types.ts
  packages/scenes/src/core/utils.ts
  packages/scenes/src/services/UrlSyncManager.ts
  packages/scenes/src/variables/sets/SceneVariableSet.ts
Labels: minor

#113 VizPanel: Updates to support panel context
  packages/scenes-app/src/pages/Demos/getDemos.ts
  packages/scenes-app/src/pages/Demos/scenes/panelContext.tsx
  packages/scenes-app/src/pages/Home/Home.tsx
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/components/VizPanel/colorSeriesConfigFactory.test.ts
  packages/scenes/src/components/VizPanel/colorSeriesConfigFactory.ts
  packages/scenes/src/components/VizPanel/seriesVisibilityConfigFactory.test.ts
  packages/scenes/src/components/VizPanel/seriesVisibilityConfigFactory.ts
  packages/scenes/src/core/SceneDataNode.ts
  packages/scenes/src/core/types.ts
  packages/scenes/src/querying/SceneDataTransformer.ts
  packages/scenes/src/variables/interpolation/defaults.ts
Labels: minor

#122 SceneObject: Rename SceneObjectStatePlain to SceneObjectState
  packages/scenes-app/src/pages/Demos/scenes/flexLayout.tsx
  packages/scenes-app/src/pages/Home/CustomSceneObject.tsx
  packages/scenes/src/components/EmbeddedScene.tsx
  packages/scenes/src/components/NestedScene.tsx
  packages/scenes/src/components/SceneApp/types.ts
  packages/scenes/src/components/SceneByFrameRepeater.tsx
  packages/scenes/src/components/SceneCanvasText.tsx
  packages/scenes/src/components/SceneReactObject.tsx
  packages/scenes/src/components/SceneRefreshPicker.tsx
  packages/scenes/src/components/SceneTimePicker.tsx
  packages/scenes/src/components/SceneToolbarButton.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelMenu.tsx
  packages/scenes/src/components/layout/SceneFlexLayout.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
  packages/scenes/src/components/layout/grid/types.ts
  packages/scenes/src/core/SceneDataNode.ts
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/core/events.ts
  packages/scenes/src/core/types.ts
  packages/scenes/src/core/utils.ts
  packages/scenes/src/querying/SceneDataTransformer.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/services/UrlSyncManager.test.ts
  packages/scenes/src/variables/TestScene.ts
  packages/scenes/src/variables/VariableDependencyConfig.test.ts
  packages/scenes/src/variables/VariableDependencyConfig.ts
  packages/scenes/src/variables/components/VariableValueSelectors.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/types.ts
Labels: minor, release

#123 ValueMacro: Fixes so __value works for rowIndex 0
  packages/scenes/src/variables/macros/DataValueMacro.test.ts
  packages/scenes/src/variables/macros/DataValueMacro.ts
Labels: patch

#43 QueryEditor: Adds inline query editor scene object
  packages/scenes-app/src/components/QueryEditor/QueryEditor.tsx
  packages/scenes-app/src/components/QueryEditor/QueryEditorRenderer.tsx
  packages/scenes-app/src/pages/Demos/getDemos.ts
  packages/scenes-app/src/pages/Demos/scenes/queryEditor.tsx
  packages/scenes/src/core/sceneGraph.ts
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: enhancement

#71 SceneAppPage: Support dynamic pages (changing tabs, title, controls)
  packages/scenes-app/src/demos/dynamicPage.tsx
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/withDrilldown/WithDrilldown.tsx
  packages/scenes-app/src/pages/DemoListPage.tsx
  packages/scenes/CHANGELOG.md
  packages/scenes/src/components/SceneApp/SceneApp.tsx
  packages/scenes/src/components/SceneApp/SceneAppPage.tsx
  packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
  packages/scenes/src/components/SceneApp/types.ts
  packages/scenes/src/components/SceneApp/utils.ts
  packages/scenes/src/components/SceneControlWrapper.tsx
  packages/scenes/src/services/UrlSyncManager.ts
Labels: enhancement

#129 SceneGridLayout: Support lazy rendering of items out of view
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/lazyLoad.tsx
  packages/scenes/src/components/layout/grid/LazyLoader.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
  packages/scenes/utils/setupTests.ts
Labels: enhancement

#148 SceneObjectBase: Activate parents before children
  packages/scenes/src/core/SceneComponentWrapper.tsx
Labels: minor

#119 Behaviors: Add state and runtime behavior to any scene object
  packages/scenes-app/src/components/SceneRadioToggle.tsx
  packages/scenes-app/src/demos/behaviors/HiddenForTimeRangeBehavior.ts
  packages/scenes-app/src/demos/behaviors/HiddenLayoutItemBehavior.ts
  packages/scenes-app/src/demos/behaviors/HiddenWhenNoDataBehavior.ts
  packages/scenes-app/src/demos/behaviors/ShowBasedOnConditionBehavior.ts
  packages/scenes-app/src/demos/behaviors/behaviorsDemo.tsx
  packages/scenes-app/src/demos/index.ts
  packages/scenes/src/components/layout/SceneFlexLayout.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/core/types.ts
Labels: minor, release

#151 Fix link in changelog
  CHANGELOG.md
  packages/scenes/CHANGELOG.md
Labels: no-changelog

#154 VizPanel: Support runtime registered panel plugins
  docusaurus/docs/visualizations.md
  docusaurus/website/sidebars.js
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/runtimePanelPlugin.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/components/VizPanel/registerRuntimePanelPlugin.ts
  packages/scenes/src/index.ts
Labels: minor

#158 VizPanel: Support noPadding panel plugins
  packages/scenes-app/src/demos/flexLayout.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: minor

#161 SceneObjectBase: Fixes issue with useState subscription misses state change that happens between frist render and useEffect
  packages/scenes/src/core/SceneObjectBase.tsx
Labels: minor, release

#163 Scenes app: add script step to build scenes
  scripts/demo.sh
Labels: no-changelog
