Repository grafana/scenes, pull requests merged in 2023-10, with the labels that each got.

#365 Variables: Implement Interval Variable
  packages/scenes-app/src/demos/variables.tsx
  packages/scenes/src/index.ts
  packages/scenes/src/variables/constants.ts
  packages/scenes/src/variables/variants/IntervalVariable.test.ts
  packages/scenes/src/variables/variants/IntervalVariable.tsx
Labels: minor, area/variables

#385 SceneFlexLayout: Export SceneFlexItemLike
  packages/scenes/src/index.ts
Labels: patch, release

#381 SceneAppPageView: Fixes react and scene state missmatch
  packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
Labels: release

#382 AdhocFilters: Pass filters via request object
  packages/scenes-app/src/demos/adhocFiltersDemo.tsx
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersSet.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersSet.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
Labels: minor, release

#377 AdhocFilters: Add docs for AdhocFilterSet and AdhocFiltersVariable
  docusaurus/docs/advanced-adhoc-fIlters.md
  docusaurus/docs/advanced-adhoc-fIlters.tsx
  docusaurus/website/sidebars.js
Labels: minor

#374 SceneTimeRange: Implement onZoom behavior
  packages/scenes/src/components/SceneTimePicker.test.tsx
  packages/scenes/src/components/SceneTimePicker.tsx
Labels: type/enhancement, patch, release

#390 Compatability: Add global window object that points to the current active EmbeddedScene
  packages/scenes/src/components/EmbeddedScene.test.tsx
  packages/scenes/src/components/EmbeddedScene.tsx
  packages/scenes/src/components/SceneApp/SceneApp.test.tsx
  packages/scenes/src/utils/compatibility/patchTimeSrv.test.tsx
  packages/scenes/src/utils/compatibility/patchTimeSrv.ts
  packages/scenes/src/utils/compatibility/setWindowGrafanaSceneContext.test.tsx
  packages/scenes/src/utils/compatibility/setWindowGrafanaSceneContext.ts
Labels: minor, release

#391 Variables: Fix issue with all value state and no options
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
  packages/scenes/src/variables/variants/TestVariable.tsx
Labels: minor, release

#394 TextBoxVariable: Fixes and make it auto size
  packages/scenes/src/variables/TestScene.ts
  packages/scenes/src/variables/components/VariableValueInput.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/variants/TextBoxVariable.test.tsx
  packages/scenes/src/variables/variants/TextBoxVariable.tsx
Labels: minor

#395 QueryVariable: Support for queries that contain "$__searchFilter"
  docusaurus/docs/variables.tsx
  packages/scenes-app/src/demos/variables.tsx
  packages/scenes/src/variables/VariableDependencyConfig.ts
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/constants.ts
  packages/scenes/src/variables/utils.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
  packages/scenes/src/variables/variants/query/createQueryVariableRunner.ts
  packages/scenes/src/variables/variants/query/toMetricFindValues.ts
Labels: minor

#398 QueryVariable: Fix sort default value
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: minor

#403 Markup: element data keys changes
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: minor, release

#407 Scenes: Interval Variable now considers $__auto_interval
  packages/scenes/src/variables/variants/IntervalVariable.tsx
Labels: patch, release, area/variables

#405 SceneVariableSet: isVariableLoadingOrWaitingToUpdate should ignore isActive state
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
Labels: minor, release

#408 SceneTimePicker: Add posibility to navigate backwards/forwards an absolute time range
  packages/scenes/src/components/SceneTimePicker.test.tsx
  packages/scenes/src/components/SceneTimePicker.tsx
Labels: minor, release

#409 VizPanel: Adds extendPanelContext so that consumers can control some of the PanelContext functions
  docusaurus/docs/visualizations.md
  packages/scenes/CHANGELOG.md
  packages/scenes/src/behaviors/CursorSync.ts
  packages/scenes/src/components/SceneTimePicker.test.tsx
  packages/scenes/src/components/SceneTimePicker.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: minor, release

#411 AdHocVariable: Fixes trailing comma
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: minor, release

#413 SceneTimeRange: Respect time zone when updating time range
  packages/scenes/src/core/SceneTimeRange.tsx
Labels: patch, release

#420 SceneTimeRange: Respect time zone when updating time range
  packages/scenes/src/core/SceneTimeRange.tsx
Labels: type/bug, patch, release

#426 Website: Update theme for alerts
  docusaurus/website/src/css/custom.css
Labels: type/documentation, no-changelog

#437 VizPanel: Allow title items configuration
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: patch, release
