Repository grafana/scenes, pull requests merged in 2024-10, with the labels that each got.

#923 Refresh: Improve / harden refresh url sync
  packages/scenes/src/components/SceneRefreshPicker.test.ts
  packages/scenes/src/components/SceneRefreshPicker.tsx
Labels: patch, release

#929 Annotations: Include templateSrv.getVariables with dashboard object in legacy annotation queries
  packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts
Labels: minor, release, area/variables

#930 Emit RefreshEvent on annotation enable/disable
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.tsx
Labels: minor, release

#928 VizPanel: Fixes issue with viz panel when passing it SceneDataTransformer
  packages/scenes-react/src/components/VizPanel.tsx
Labels: type/bug, patch, release

#931 Interpolation: Fixes queryparam variable format when used with adhoc filter variable
  packages/scenes/src/variables/interpolation/formatRegistry.test.ts
  packages/scenes/src/variables/interpolation/formatRegistry.ts
  packages/scenes/src/variables/macros/AllVariablesMacro.test.ts
Labels: patch, release

#914 Add checks for valid dates before saving calculating values
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/utils/date.ts
  packages/scenes/src/utils/parseUrlParam.test.ts
  packages/scenes/src/utils/parseUrlParam.ts
Labels: patch, release

#932 PanelBuilders: Mixin function to share config
  docusaurus/docs/visualizations.md
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
Labels: minor, release

#933 Fix a crash when refresh interval set to empty string
  packages/scenes/src/components/SceneRefreshPicker.test.ts
  packages/scenes/src/components/SceneRefreshPicker.tsx
Labels: type/bug, release

#934 VizPanel: Fix issue where changing panel options wouldn't cause re-render
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: type/bug, minor, patch, release

#925 SceneContextObject: Export context object
  packages/scenes-react/src/index.ts
Labels: patch, release

#927 AdHocFiltersCombobox: adjust combobox filter values when switching between multi and single operators
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
Labels: patch, release, area/variables

#941 feat: sort adhoc filter options using ufuzzy
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
  packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.test.ts
  packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.ts
  packages/scenes/src/variables/components/getOptionSearcher.test.ts
  packages/scenes/src/variables/components/getOptionSearcher.ts
Labels: patch, release, area/variables

#944 SceneObject: Improve cloning logic
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/sceneGraph/utils.ts
Labels: minor, release

#942 AdHocFilterCombobox: Improve backspace functionality to delete filter key, operator and values separately
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersComboboxRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: patch, release, area/variables
