Repository grafana/scenes, pull requests merged in 2024-09, with the labels that each got.

#886 SceneTimeRange: Support initialize time range with time and time.window
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/core/types.ts
Labels: minor, release, usecase/core-dashboards, type/feature-request

#878 UrlSync: Support browser history steps, remove singleton
  docusaurus/docs/scene-app.md
  docusaurus/docs/url-sync.md
  docusaurus/website/sidebars.js
  packages/scenes-app/src/demos/urlSyncTest.tsx
  packages/scenes-app/src/pages/DemoListPage.tsx
  packages/scenes-react/src/contexts/SceneContextObject.tsx
  packages/scenes-react/src/contexts/SceneContextProvider.tsx
  packages/scenes/src/components/SceneApp/SceneApp.tsx
  packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
  packages/scenes/src/components/SceneApp/types.ts
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/core/sceneGraph/index.ts
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
  packages/scenes/src/core/types.ts
  packages/scenes/src/index.ts
  packages/scenes/src/services/SceneObjectUrlSyncConfig.ts
  packages/scenes/src/services/UrlSyncContextProvider.ts
  packages/scenes/src/services/UrlSyncManager.test.ts
  packages/scenes/src/services/UrlSyncManager.ts
  packages/scenes/src/services/useUrlSync.ts
  packages/scenes/utils/test/updateUrlStateAndSyncState.tsx
Labels: minor, release

#887 SceneObjectBase: Support rendering a child out of context
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/SceneObjectBase.tsx
Labels: minor, release

#890 TextBoxVariable: fixes issues with TextBox variable when being updated by URL
  packages/scenes/src/variables/components/VariableValueInput.tsx
  packages/scenes/src/variables/variants/TextBoxVariable.tsx
Labels: minor, patch

#889 AdHocFilters - multi value support in new filters UI
  packages/scenes-app/src/demos/adhocFiltersDemo.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersComboboxRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/DropdownItem.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/useFloatingInteractions.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: patch, release, area/variables

#892 SceneObjectBase: add clearParent
  packages/scenes/src/core/SceneObjectBase.tsx
Labels: patch, release

#896 MultiValueVariabe: Change when value changed event is published
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
  packages/scenes/src/variables/variants/TestVariable.tsx
Labels: patch, release

#900 Include isMulti and includeAll in LocalValueVariable
  packages/scenes/src/variables/variants/LocalValueVariable.ts
Labels: release

#898 AdHocVariable: Don't throw when operator is not found
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: type/bug, patch, release

#903 DataProvideSharer: Add and export DataProviderSharer
  docusaurus/docs/advanced-data.md
  packages/scenes-react/src/components/VizPanel.tsx
  packages/scenes-react/src/hooks/useDataTransformer.ts
  packages/scenes/src/index.ts
  packages/scenes/src/querying/DataProviderSharer.ts
Labels: patch, release

#910 SceneTimeRange: Use new weekStart prop on TimeRangePicker
  packages/scenes/src/components/SceneTimePicker.tsx
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
Labels: minor, release

#907 SceneTimeRange: Fixes inconsistent representation of time range
  packages/scenes/src/core/SceneTimeRange.tsx
Labels: patch, release

#915 SceneTimePicker: Implement recently used absolute time ranges view
  packages/scenes/src/components/SceneTimePicker.test.tsx
  packages/scenes/src/components/SceneTimePicker.tsx
Labels: minor, release, area/tests
