Repository grafana/scenes, pull requests merged in 2024-07, with the labels that each got.

#812 Revert "VizPanel: Load plugin prefered default options when activating"
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: patch, release

#814 Revert "SceneRefreshPicker: Fixes url state issue (#784)"
  packages/scenes/src/components/SceneRefreshPicker.tsx
Labels: type/bug, patch, release

#815 Adhoc filters: Fix regression with displaying groups
  packages/scenes/jest.config.ts
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.test.ts
  packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.ts
  packages/scenes/utils/test/__mocks__/style.ts
Labels: type/bug, patch, release

#802 Dependencies: Bump grafana packages to v11
  packages/scenes-app/package.json
  packages/scenes-react/package.json
  packages/scenes/package.json
  yarn.lock
Labels: patch, release, dependencies

#823 LazyLoader: Hide wrapper if child is hidden
  packages/scenes-app/src/demos/cssGridLayoutDemo.tsx
  packages/scenes/src/components/layout/CSSGrid/SceneCSSGridLayout.tsx
  packages/scenes/src/components/layout/LazyLoader.tsx
Labels: patch, release

#832 Add variable dependency config to SceneGridRow
  packages/scenes/src/components/layout/grid/SceneGridRow.tsx
Labels: patch

#816 Adhoc filters/Group by: Support groups
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/types.ts
  packages/scenes/src/variables/utils.ts
Labels: minor, release

#833 fix(lazyloader): fix trying to run inexistent callbacks
  packages/scenes/src/components/layout/LazyLoader.tsx
Labels: type/bug

#837 QueryVariable: Query is empty string by default
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: type/bug, patch, release, usecase/core-dashboards

#836 Scenes: Move change panel plugin logic in VizPanel
  packages/scenes-app/src/demos/dynamicPanelOptions.tsx
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: minor, release

#838 Add triggering RefreshEvent on time range refresh
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/querying/SceneDataTransformer.test.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
Labels: type/bug, patch, release, usecase/core-dashboards

#828 Wrap __sceneObject scoped var in an serialisable wrapper
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.tsx
  packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts
  packages/scenes/src/utils/SafeSerializableSceneObject.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: minor, release

#835 SceneTimeRange: Allow time range refresh on activation
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/core/types.ts
Labels: type/bug, patch, release

#844 SafeSerializableSceneObject: Make sure valueOf is bound to the instance
  packages/scenes/src/utils/SafeSerializableSceneObject.test.ts
  packages/scenes/src/utils/SafeSerializableSceneObject.ts
Labels: patch, release

#849 Allow setting _skipOnLayoutChange in SceneGridLayout
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
Labels: minor, release

#850 SceneVariableSet: Update all variables in case of error
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
Labels: patch, release, area/variables

#852 VizPanel: React to RefreshEvent for non-data changes
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
Labels: type/bug, patch, release, usecase/core-dashboards
