Repository grafana/scenes, pull requests merged in 2024-12, with the labels that each got.

#985 Variables: Fixes issue when variable value was null
  packages/scenes/src/variables/components/VariableValueSelect.test.tsx
  packages/scenes/src/variables/variants/query/toMetricFindValues.ts
  packages/scenes/src/variables/variants/query/utils.test.ts
  packages/scenes/src/variables/variants/query/utils.ts
Labels: type/bug, minor

#808 VizPanel: support collapsible props
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
Labels: minor, release, no-changelog

#991 Lint: scenes/pull/808
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
Labels: no-changelog

#992 AdHocFiltersCombobox - Improve filter editing behaviour when pre-filling value on edit
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
Labels: minor, release, area/variables

#997 VizPanel: Set selectionId for PanelChrome
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: minor, release

#998 feat: (scenes-react) - VizPanel add missing props and tests
  packages/scenes-react/src/components/VizPanel.test.tsx
  packages/scenes-react/src/components/VizPanel.tsx
Labels: minor, release

#981 Supply fixed now to datemath caluclations
  packages/scenes/src/utils/evaluateTimeRange.ts
Labels: minor, release

#1002 SceneTimeRange: Fixes weekstart issue when evaluting data math
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
Labels: minor, release

#996 Variables: Interpolate datasource uid when used with datasource variable
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/variables/adhoc/patchGetAdhocFilters.ts
  packages/scenes/src/variables/groupby/findActiveGroupByVariablesByUid.ts
  packages/scenes/src/variables/utils.test.ts
  packages/scenes/src/variables/utils.ts
Labels: patch, release, area/variables

#1007 SceneTimeRange: Set weekstart when evaluating time range
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/core/SceneTimeZoneOverride.tsx
  packages/scenes/src/utils/evaluateTimeRange.ts
Labels: minor, release

#1004 AdHocFiltersVariable: provide updateFilters method to allow updating filters without emitting SceneVariableValueChangedEvent
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: minor, release

#1018 AdHocFilters: Fix matching non-latin template vars in filter
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
  packages/scenes/src/variables/utils.test.ts
Labels: patch, release, area/variables
