Repository grafana/scenes, pull requests merged in 2024-03, with the labels that each got.

#626 Rows are draggable when scene layout is draggable
  packages/scenes/src/components/layout/grid/SceneGridRow.tsx
Labels: patch, release

#628 SceneObjectBase: Call self activation handlers before child data, time range and variable handlers
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.ts
Labels: minor

#636 VizPanel: Fixes issue updating field config
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: patch, release

#632 Variables: Maintain custom (invalid) variable values set via URL on initial load
  packages/scenes/src/variables/sets/SceneVariableSet.ts
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: minor, release

#612 Variables: Support static keys in AdHocFiltersVariable
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: minor, release

#638 PanelMigrations: Fixes incorrect panel.id in migration handler
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: minor, release

#641 LiveNow: Fixes activation/deactivation issue and logic error with getTimeRange
  packages/scenes/src/behaviors/LiveNowTimer.ts
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: type/bug

#643 VizPanel: Fixes incrementing structureRev
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: patch, release

#644 SceneGridLayout: Fixes moving panels when opening dashboards
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: patch, release

#645 AdHocFilter: Correctly show the label for a matching default key
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: type/bug, patch

#651 Add transformations to annotations dataframes
  packages/scenes/src/core/types.ts
  packages/scenes/src/querying/SceneDataTransformer.test.ts
  packages/scenes/src/querying/SceneDataTransformer.ts
Labels: minor, release

#640 DataLayers: Unifiy DataLayers (group of data layers) and a single data layer
  packages/scenes-app/src/demos/annotations.tsx
  packages/scenes-app/src/demos/dynamicDataLayers.tsx
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/queryController.tsx
  packages/scenes/src/core/sceneGraph/sceneGraph.test.tsx
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
  packages/scenes/src/core/types.ts
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneDataLayerSet.tsx
  packages/scenes/src/querying/SceneDataLayers.ts
  packages/scenes/src/querying/SceneDataTransformer.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/layers/SceneDataLayerBase.test.ts
  packages/scenes/src/querying/layers/SceneDataLayerBase.ts
  packages/scenes/src/querying/layers/SceneDataLayerControls.test.tsx
  packages/scenes/src/querying/layers/SceneDataLayerControls.tsx
  packages/scenes/src/querying/layers/TestDataLayer.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.tsx
  packages/scenes/src/querying/mergeMultipleDataLayers.ts
Labels: major, release

#655 Core: Fixes type issue introduced by merge
  packages/scenes/src/core/types.ts
Labels: release, no-changelog

#652 SceneQueryRunner: Meaningful cloning
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: type/bug, patch, release

#653 Chore: Bump to yarn 4
  .github/actions/yarn-nm-install/action.yml
  .github/workflows/deploy-to-dev-portal-dev.yml
  .github/workflows/deploy-to-dev-portal-prod.yml
  .github/workflows/node-ci.yml
  .yarn/releases/yarn-3.3.1.cjs
  .yarn/releases/yarn-4.1.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: patch, release, dependencies

#656 MultiValueVariable: Fixes issue with initial url sync when using old All url value
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: patch, release

#660 Check if target datasource is matching the panel ds, if not set the target ds to panel ds.
  packages/scenes/src/querying/SceneDataTransformer.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: patch, release
