Repository grafana/scenes, pull requests merged in 2024-04, with the labels that each got.

#663 Fix drag and drop panels in rows
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
Labels: patch, release

#665 AdHocFiltersVariable/GroupByVariable: Pass time range to getTagKeys calls
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  yarn.lock
Labels: patch, release

#666 Fix issue where curly braces are always added to IntervalMacro.
  packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts
  packages/scenes/src/variables/macros/timeMacros.test.ts
  packages/scenes/src/variables/macros/timeMacros.ts
Labels: patch, release, area/variables

#658 Autofit: Fit widget in the screen depending on the height
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
  packages/scenes/src/components/layout/grid/utils.test.ts
  packages/scenes/src/components/layout/grid/utils.ts
Labels: minor, release, usecase/core-dashboards, type/feature-request

#667 SceneRefreshPicker: Implement mechanism for auto interval
  packages/scenes/src/components/SceneRefreshPicker.test.ts
  packages/scenes/src/components/SceneRefreshPicker.tsx
Labels: minor, release

#675 Chore: Remove viz panel tooltip related code that is no longer needed
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: type/bug, patch, release

#659 VizPanel: Do not apply the visualization's field config to annotation data frames
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: minor, release

#657 Chore: Bump typescript version
  docusaurus/website/package.json
  packages/scenes-app/package.json
  packages/scenes-app/src/demos/dynamicPanelOptions.tsx
  packages/scenes-app/tsconfig.json
  packages/scenes/package.json
  packages/scenes/src/components/SceneApp/utils.ts
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/variants/query/createQueryVariableRunner.ts
  packages/scenes/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: patch, release, dependencies

#671 Disallow drag and drop rows within uncollapsed rows
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: patch, release

#680 SceneRefreshPicker: Show the auto calculated value when auto is selected
  packages/scenes/src/components/SceneRefreshPicker.test.ts
  packages/scenes/src/components/SceneRefreshPicker.tsx
Labels: patch, release

#681 Clone SceneQueryRunner together with _results
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: patch, release

#674 VizPanel: Allow configuring hover header offset
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: patch, release

#685 Filters/GroupBy: Resolve queries only from active query runners
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/utils.test.ts
  packages/scenes/src/variables/utils.ts
Labels: patch, release

#688 SceneObjectBase: useState add options that make the new activation behavior optional
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/core/types.ts
  packages/scenes/src/index.ts
  packages/scenes/src/variables/components/VariableValueSelectors.tsx
Labels: minor, release

#692 SceneComponentWrapper: More robust activation
  packages/scenes/src/core/SceneComponentWrapper.tsx
Labels: minor, release

#691 LocalValueVariable: Do not throw when missing parent variable
  packages/scenes/src/variables/variants/LocalValueVariable.test.ts
  packages/scenes/src/variables/variants/LocalValueVariable.ts
Labels: minor, release

#635 Annotations: Don't always execute annotations on activate
  packages/scenes/src/querying/layers/SceneDataLayerBase.test.ts
  packages/scenes/src/querying/layers/SceneDataLayerBase.ts
Labels: minor, release

#695 RefreshPicker: Fixed width when going betwen normal and loading state
  packages/scenes/src/components/SceneRefreshPicker.tsx
Labels: minor, release

#698 Fix ${__all_variables} not updating their value in panels
  packages/scenes/src/variables/VariableDependencyConfig.ts
Labels: type/bug, minor, release, area/variables

#701 Interval variable: Make interval variable properly update on name change
  packages/scenes/src/variables/variants/IntervalVariable.tsx
Labels: patch, release

#687 GroupBy: Fetch options when opening menu
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
  packages/scenes/src/variables/types.ts
  packages/scenes/src/variables/utils.test.ts
  packages/scenes/src/variables/utils.ts
  packages/scenes/src/variables/variants/TestVariable.tsx
Labels: patch, release

#690 AdhocFilters: Show label for selected key
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFilterValue.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
Labels: patch, release

#702 VizPanel: Fixes issue updating instanceState
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: minor, release

#704 Fix how the submenus appear for menus of type group
  packages/scenes/src/components/VizPanel/VizPanelMenu.tsx
Labels: patch, release

#707 SceneQueryRunner: Support detecting new local time range
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: release

#648 Dashboard Migration: Add missing e2e selectors to some components
  packages/scenes/src/components/VizPanel/VizPanelMenu.tsx
  packages/scenes/src/components/layout/grid/SceneGridRow.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/components/VariableValueSelectors.tsx
Labels: patch, release, area/tests

#708 sceneGraph: handle interpolations argument in interpolate
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
  packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts
  packages/scenes/src/variables/interpolation/sceneInterpolator.ts
Labels: minor, release
