Repository grafana/scenes, pull requests merged in 2024-01, with the labels that each got.

#519 SceneQueryRunner: Fix redundant execution on variable change
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: type/bug

#515 Fix issue with duplicate annotations
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: type/bug

#509 SceneTimeRange: Support delay now to avoid data drops in charts
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/core/SceneTimeZoneOverride.tsx
  packages/scenes/src/core/types.ts
  packages/scenes/src/utils/evaluateTimeRange.ts
Labels: usecase/core-dashboards

#531 SplitLayout: Allow pane style overrides to be passed through
  packages/scenes/src/components/layout/split/SplitLayout.ts
  packages/scenes/src/components/layout/split/SplitLayoutRenderer.tsx
Labels: minor

#532 Chore: Update peer dependencies
  packages/scenes-app/package.json
  packages/scenes/package.json
Labels: minor, dependencies, no-changelog

#530 SceneGridLayout: Support new visualization tooltips
  packages/scenes-app/src/demos/grid.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: minor, release

#529 UrlSync: Export new util functions
  packages/scenes/CHANGELOG.md
  packages/scenes/src/index.ts
  packages/scenes/src/services/UniqueUrlKeyMapper.ts
  packages/scenes/src/services/UrlSyncManager.test.ts
  packages/scenes/src/services/UrlSyncManager.ts
  packages/scenes/src/services/utils.test.ts
  packages/scenes/src/services/utils.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: minor

#543 SceneDataTransformer: Fixes issue with getResultStream not emitting values when there are no transformations
  packages/scenes/src/querying/SceneDataTransformer.test.ts
  packages/scenes/src/querying/SceneDataTransformer.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: minor

#540 Fixes issue with exemplar link
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: minor

#549 LocalValueVariable: Provide backwards compatibility for SQL-ish data source
  packages/scenes/src/variables/variants/LocalValueVariable.ts
Labels: patch, release

#544 AdHocFiltersSet: Pass scene queries to getTagKeys calls
  packages/scenes/src/core/sceneGraph/index.ts
  packages/scenes/src/core/sceneGraph/sceneGraph.test.tsx
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersSet.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersSet.tsx
Labels: minor

#550 AdHocFiltersVariable: AdHocFilterSet is not activated when the parent variable is mounted
  package.json
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  yarn.lock
Labels: type/bug, patch, release, area/variables

#553 AdHocFiltersVariable: The `create()` factory supports `applyMode` as parameter
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: type/enhancement, patch, release, usecase/core-dashboards, area/variables

#554 Fix dataLayer subscriptions refresh on reactivation
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/layers/SceneDataLayerBase.ts
Labels: patch, release, usecase/core-dashboards
