Repository grafana/scenes, pull requests merged in 2024-06, with the labels that each got.

#753 feat: sceneGraph.findByKey(AndType)
  packages/scenes/src/core/sceneGraph/index.ts
  packages/scenes/src/core/sceneGraph/sceneGraph.test.tsx
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
Labels: type/enhancement, minor, release, no-changelog

#763 Variables: Search / typing performance improvements
  packages/scenes-app/src/demos/variables.tsx
  packages/scenes/package.json
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/components/getOptionSearcher.test.ts
  packages/scenes/src/variables/components/getOptionSearcher.ts
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  yarn.lock
Labels: release

#771 fix: downgrade workspace prettier to 2.5.1
  package.json
  yarn.lock
Labels: release, no-changelog

#774 Variables: Support variable expressions inside custom values
  packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts
  packages/scenes/src/variables/interpolation/sceneInterpolator.ts
Labels: type/bug, release

#770 VariableValueSelect: Adjust data-testid in OptionWithCheckbox
  packages/scenes/package.json
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  yarn.lock
Labels: patch, release

#766 AdHocFiltersVariable: Performance improvements
  packages/scenes-app/src/demos/variables.tsx
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/components/getOptionSearcher.test.ts
  packages/scenes/src/variables/components/getOptionSearcher.ts
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
Labels: minor, release

#776 SceneQueryRunner: Do not set panelId by default
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: minor, release

#779 Introduce enrichFiltersRequest
  packages/scenes/src/core/types.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/getEnrichedFiltersRequest.ts
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
Labels: minor, release, area/variables

#781 Variables: Add support to read only variables and expose missing types for custom variables in core grafana
  packages/scenes/src/index.ts
  packages/scenes/src/variables/components/VariableValueSelect.test.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: minor, release, area/variables

#784 SceneRefreshPicker: Fixes url state issue
  packages/scenes/src/components/SceneRefreshPicker.tsx
Labels: minor

#785 Variables: Fixes sceneInterpolator when string contains variables with object prototype function names
  packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts
  packages/scenes/src/variables/interpolation/sceneInterpolator.ts
  packages/scenes/src/variables/macros/index.ts
Labels: minor, release

#783 AdHocFiltersVariable: Show operator in vertical mode
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: minor, release, area/variables

#765 UrlSync: Major refactoring to simplify and make it work better across page routes (for scenes-react use case)
  package.json
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/urlSyncTest.tsx
  packages/scenes-app/src/pages/DemoListPage.tsx
  packages/scenes-app/src/react-demo/DrilldownDemoPage.tsx
  packages/scenes-app/src/react-demo/Home.tsx
  packages/scenes-react/src/contexts/SceneContextObject.test.tsx
  packages/scenes-react/src/contexts/SceneContextObject.tsx
  packages/scenes-react/src/contexts/SceneContextProvider.test.tsx
  packages/scenes-react/src/contexts/SceneContextProvider.tsx
  packages/scenes/src/components/EmbeddedScene.tsx
  packages/scenes/src/components/SceneApp/SceneAppPage.tsx
  packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
  packages/scenes/src/index.ts
  packages/scenes/src/services/UniqueUrlKeyMapper.ts
  packages/scenes/src/services/UrlSyncContextProvider.ts
  packages/scenes/src/services/UrlSyncManager.test.ts
  packages/scenes/src/services/UrlSyncManager.ts
  packages/scenes/src/services/useUrlSync.ts
  packages/scenes/src/services/utils.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/utils/test/TestContextProvider.tsx
  packages/scenes/utils/test/updateUrlStateAndSyncState.tsx
Labels: major, release

#793 UrlSync: Fixes issue with recent url sync change
  packages/scenes/package.json
  packages/scenes/src/services/UrlSyncManager.test.ts
  packages/scenes/src/services/UrlSyncManager.ts
  packages/scenes/src/services/utils.ts
  yarn.lock
Labels: patch, release

#794 UrlSync: Remove console.log left in prev PR
  packages/scenes/src/services/UrlSyncManager.ts
Labels: patch, release

#795 Data layers: Don't run layer on activation if disabled
  packages/scenes/src/querying/layers/SceneDataLayerBase.test.ts
  packages/scenes/src/querying/layers/SceneDataLayerBase.ts
Labels: type/bug, patch, release

#790 Add support for new getTagKeys/getTagValues interface
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/utils.ts
Labels: minor, release

#797 VariableValueSelect: Hardcode flaky Select option e2e-selector
  packages/scenes/src/variables/components/VariableValueSelect.tsx
Labels: type/bug, patch, release

#796 Scenes: Return value if not string in interpolator
  packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts
  packages/scenes/src/variables/interpolation/sceneInterpolator.ts
Labels: patch, release

#801 VizPanel: Clear options value when the option is undefined
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
Labels: type/bug, patch, release, usecase/core-dashboards

#800 Add `toAbsolute` method to SceneTimePicker
  packages/scenes/src/components/SceneTimePicker.test.tsx
  packages/scenes/src/components/SceneTimePicker.tsx
Labels: minor, release

#805 VizPanel: Allow to adapt color palette after plugin change
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: type/bug, patch, release, usecase/core-dashboards

#806 VizPanel: Load plugin prefered default options when activating
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: type/bug, patch, release, usecase/core-dashboards
