Repository grafana/scenes, pull requests merged in 2024-11, with the labels that each got.

#952 Don't run migration when changing panel plugin
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: release

#950 VizPanel: Add flag to decide whether configs should be refreshed on `changePluginType`
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: minor, release

#953 SceneObject: Cloning with state fix
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/sceneGraph/utils.ts
Labels: patch, release

#947 SceneTimeRange: Fix passing timezone URL parameter
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/services/UrlSyncManager.test.ts
  packages/scenes/src/variables/interpolation/sceneInterpolator.test.ts
  packages/scenes/src/variables/macros/timeMacros.test.ts
  packages/scenes/src/variables/macros/timeMacros.ts
Labels: patch, release

#954 VizPanel: Adjust forceRender logic
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: type/bug, minor, release

#955 AdHocFiltersCombobox - Pre-fill filter combobox value on edit
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/MultiValuePill.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
Labels: patch, release, area/variables

#959 Variables: Saved default all value with non multi select fix
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: patch, release

#963 VariableLabel: change variable label check to OR instead of ??
  packages/scenes/src/variables/components/VariableValueSelectors.tsx
Labels: patch, release, area/variables

#958 New filters UI: adds some basic unit tests
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
Labels: patch, release

#960 Variables: Add new `allowCustomValue` flag to AdHoc Variable
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: minor, release

#956 Variables: Add new `allowCustomValue` flag to MultiVariables
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/components/VariableValueSelect.test.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: minor, release

#940 Chore: Relax dependencies and move e2e-selectors to peerDeps
  packages/scenes-react/package.json
  packages/scenes/package.json
  yarn.lock
Labels: minor, release, dependencies

#969 Variables: Fix search result ordering to use match quality
  packages/scenes/package.json
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
  packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.ts
  packages/scenes/src/variables/components/getOptionSearcher.ts
  packages/scenes/src/variables/utils.test.ts
  packages/scenes/src/variables/utils.ts
  yarn.lock
Labels: type/enhancement, area/variables

#964 Annotations: Fix issue where dashboard annotations weren't rendering
  packages/scenes/src/querying/layers/annotations/filterAnnotations.ts
Labels: type/bug, patch, release

#970 Add missing parameter to patchGetAdhocFilters.ts
  packages/scenes/src/variables/adhoc/patchGetAdhocFilters.ts
Labels: patch, release

#968 SceneObject: Render before activation
  packages/scenes/src/components/SceneControlsSpacer.tsx
  packages/scenes/src/core/SceneComponentWrapper.test.tsx
  packages/scenes/src/core/SceneComponentWrapper.tsx
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/core/types.ts
Labels: minor, release

#978 VizPanel: Limit series feature
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/seriesLimit.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/components/VizPanel/VizPanelSeriesLimit.tsx
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.test.ts
  packages/scenes/src/core/PanelBuilders/VizPanelBuilder.ts
Labels: minor, release

#982 AdHocFiltersCombobox: Prevent updating combobox options when input type changed during fetch
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
Labels: type/bug, patch, release, area/variables
