Repository grafana/scenes, pull requests merged in 2024-05, with the labels that each got.

#712 MultiValueVariable: Fixes support for legacy All url value
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: patch, release

#713 AdHocFiltersVariable: create an opt-in state variable for using queries to filter the options
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: type/enhancement, minor, release

#715 Allow filter selectors to wrap
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: type/bug, patch, release

#721 AdHoc filters: Allow adding custom value while loading
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
Labels: type/enhancement, patch, release

#720 SceneDataTransformer: Fixes transformer emitting untransformed series
  packages/scenes/src/querying/SceneDataTransformer.test.ts
  packages/scenes/src/querying/SceneDataTransformer.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: minor, release

#719 Types: Export `FieldConfigOverridesBuilder`
  packages/scenes/src/core/PanelBuilders/index.ts
  packages/scenes/src/index.ts
Labels: minor, release

#709 VariableSelect: Multi select design update and behavior improvements
  packages/scenes-app/src/demos/variables.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
Labels: minor, release

#722 AdHoc filters: Apply `isKeysOpen` state changes synchronously
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
Labels: patch, release

#714 AdHocFilters: clear filter value when key is changed
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/variables/adhoc/AdHocFilterValue.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
Labels: type/bug, patch, release

#723 AdHoc filters: Allow typing the same custom value
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
Labels: type/bug, patch, release

#731 SceneObject: Handle new or removed behaviors
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/SceneObjectBase.tsx
Labels: minor

#727 SceneQueryRunner: Detect new variable values when cloned
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/variables/VariableValueRecorder.ts
  tsconfig.json
Labels: minor, release

#726 Variables: Do not update value when value and text are the same
  packages/scenes/src/querying/SceneDataTransformer.test.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
  packages/scenes/utils/test/utils.tsx
Labels: minor

#725 SceneDataTransformer: Performance optimizations
  packages/scenes/src/querying/SceneDataTransformer.test.ts
  packages/scenes/src/querying/SceneDataTransformer.ts
Labels: minor, release

#733 SceneGridLayout: Prevent panels from moving on mount
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: minor

#728 Typescript: Enable strict mode
  packages/scenes/src/querying/SceneDataTransformer.test.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  tsconfig.json
Labels: minor

#705 GroupByVariable: Sync label to URL
  packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/groupby/GroupByVariableUrlSyncHandler.ts
  packages/scenes/src/variables/utils.ts
Labels: minor, release, area/variables

#735 NestedScene: Don't show `cursor: pointer;` for everything
  packages/scenes/src/components/NestedScene.tsx
Labels: type/bug, patch

#729 SceneVariableSet: Do not propagate variable value changes when a local variable has the same name
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
Labels: minor, release

#736 Group by: Do not allow custom options
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
Labels: patch, release

#724 Performance: Limit data layer state updates
  packages/scenes/src/querying/DataLayersMerger.ts
  packages/scenes/src/querying/SceneDataLayerSet.tsx
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/layers/SceneDataLayerBase.ts
  packages/scenes/src/querying/layers/TestDataLayer.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.tsx
  packages/scenes/src/querying/mergeMultipleDataLayers.ts
Labels: minor, release

#738 MultiValueVariable: Fixes setting value from url when url value is a custom all value
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: minor, release

#742 VariableValueSelect: Add missing data-testids for e2e
  packages/scenes/src/variables/components/VariableValueSelect.tsx
Labels: patch, release

#749 SceneFlexLayout: Min width/height option was ignored
  packages/scenes/src/components/layout/SceneFlexLayout.tsx
Labels: minor, release

#756 Allow drag and dropping rows in valid states
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
Labels: patch, release

#757 MultiValueVariable: Fixes issue when value is all value but all value is not enabled
  packages/scenes/src/components/VizPanel/seriesVisibilityConfigFactory.test.ts
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: release

#755 ScenesReact: Move new react contexts, hooks and components to new @grafana/scenes-react package
  .github/workflows/node-ci.yml
  lerna.json
  package.json
  packages/scenes-app/package.json
  packages/scenes-app/src/demos/interopDemo.tsx
  packages/scenes-app/src/demos/utils.ts
  packages/scenes-app/src/react-demo/DrilldownDemoPage.tsx
  packages/scenes-app/src/react-demo/DynamicQueriesPage.tsx
  packages/scenes-app/src/react-demo/DynamicVariablesPage.tsx
  packages/scenes-app/src/react-demo/DynamicVisualizationPage.tsx
  packages/scenes-app/src/react-demo/Home.tsx
  packages/scenes-app/src/react-demo/InterpolationHookPage.tsx
  packages/scenes-app/src/react-demo/NestedContextPage.tsx
  packages/scenes-app/src/react-demo/PageWrapper.tsx
  packages/scenes-app/src/react-demo/PlainGraphWithRandomWalk.tsx
  packages/scenes-app/src/react-demo/RepeatBySeriesPage.tsx
  packages/scenes-app/src/react-demo/RepeatByVariablePage.tsx
  packages/scenes-app/src/react-demo/visualizations.tsx
  packages/scenes-react/.eslintrc
  packages/scenes-react/CHANGELOG.md
  packages/scenes-react/README.md
  packages/scenes-react/jest.config.ts
  packages/scenes-react/package.json
  packages/scenes-react/rollup.config.ts
  packages/scenes-react/scripts/postpack.js
  packages/scenes-react/scripts/prepack.js
  packages/scenes-react/src/DataProxyProvider.tsx
  packages/scenes-react/src/components/RefreshPicker.tsx
  packages/scenes-react/src/components/TimeRangePicker.tsx
  packages/scenes-react/src/components/VariableSelect.tsx
  packages/scenes-react/src/components/VizPanel.tsx
  packages/scenes-react/src/contexts/BreadcrumbContext.tsx
  packages/scenes-react/src/contexts/SceneContextObject.test.tsx
  packages/scenes-react/src/contexts/SceneContextObject.tsx
  packages/scenes-react/src/contexts/SceneContextProvider.test.tsx
  packages/scenes-react/src/contexts/SceneContextProvider.tsx
  packages/scenes-react/src/hooks/hooks.ts
  packages/scenes-react/src/hooks/useQueryRunner.tsx
  packages/scenes-react/src/hooks/useVariableValues.ts
  packages/scenes-react/src/index.ts
  packages/scenes-react/src/types.ts
  packages/scenes-react/src/utils.ts
  packages/scenes-react/src/variables/CustomVariable.tsx
  packages/scenes-react/tsconfig.build.json
  packages/scenes-react/tsconfig.json
  packages/scenes-react/utils/setupTests.ts
  packages/scenes-react/utils/test/__mocks__/pluginMocks.ts
  packages/scenes/src/components/EmbeddedScene.tsx
  packages/scenes/src/core/PanelBuilders/VizConfigBuilder.ts
  packages/scenes/src/core/PanelBuilders/VizConfigBuilders.ts
  packages/scenes/src/core/PanelBuilders/types.ts
  packages/scenes/src/core/types.ts
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/react-context/index.ts
  packages/scenes/src/react-context/types.ts
  packages/scenes/src/variables/utils.ts
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
  yarn.lock
Labels: release

#759 Macros: Resolve browser timezone for `$__timezone`
  packages/scenes/src/variables/macros/timeMacros.test.ts
  packages/scenes/src/variables/macros/timeMacros.ts
Labels: type/bug, patch, release, area/variables

#716 VizPanelRenderer: Emit SetPanelAttention event
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: release

#758 AdHoc filters: Add support for adhoc filter value groups
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: minor, release
