Repository grafana/scenes, pull requests merged in 2024-08, with the labels that each got.

#857 AdHocFilters: Support custom filter keys
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
Labels: patch, release

#855 SceneVariableSetTest - add test cases when one of chained variables throws errors
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
Labels: area/tests, no-changelog

#861 Add backwards compatibility for query variables referencing themselves
  packages/scenes/src/core/sceneGraph/sceneGraph.test.tsx
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
  packages/scenes/src/variables/variants/DataSourceVariable.test.ts
Labels: type/bug, patch, release

#872 SceneGridLayout: Change to useMeasure and non absolute div wrapper
  packages/scenes/src/components/layout/grid/SceneGridLayout.test.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: minor, release

#334 SceneQueryRunner: Manual control over query execution
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/services/useUrlSync.ts
  packages/scenes/src/variables/types.ts
Labels: minor, release, usecase/app-plugins

#867 PanelAttention: Fix delay
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: release

#854 SafeSerializableSceneObject: Wrap only for supported Grafana version
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/__snapshots__/SceneQueryRunner.test.ts.snap
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.tsx
  packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts
  packages/scenes/src/utils/wrapInSafeSerializableSceneObject.test.ts
  packages/scenes/src/utils/wrapInSafeSerializableSceneObject.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: minor, release

#879 Allow auto refresh only if tab is visible
  packages/scenes/src/components/SceneRefreshPicker.test.ts
  packages/scenes/src/components/SceneRefreshPicker.tsx
Labels: patch, release

#868 AdHocFilters: Add support for new `isOneOf` multi value operator
  packages/scenes-app/src/demos/adhocFiltersDemo.tsx
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
  packages/scenes/src/variables/utils.ts
Labels: type/enhancement, minor, release

#830 AdHocFiltersVariable - new ad hoc filters UI
  packages/scenes-app/src/demos/adhocFiltersDemo.tsx
  packages/scenes/package.json
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersAlwaysWipCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersComboboxRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/DropdownItem.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/useFloatingInteractions.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  yarn.lock
Labels: patch, release, area/variables
