Repository grafana/scenes, pull requests merged in 2024-02, with the labels that each got.

#557 SceneVariableSet: Cancel query when dependency changes
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
  packages/scenes/src/variables/variants/TestVariable.tsx
Labels: minor

#555 UrlSync: Fixes overwrite issue where later state change overwrites earlier change
  packages/scenes/src/services/UrlSyncManager.test.ts
  packages/scenes/src/services/UrlSyncManager.ts
  packages/scenes/src/utils/test/activateFullSceneTree.ts
Labels: minor, release

#558 POC: Group by variable
  packages/scenes-app/src/demos/groupByDemo.tsx
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/groupby/AggregationsSet.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/groupby/findActiveAggregationsSetByUid.ts
  packages/scenes/src/variables/groupby/findActiveGroupByVariablesByUid.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: area/variables

#548 Introduce GroupBy variable to allow passing group by dimensions to data sources
  packages/scenes-app/src/demos/groupByDatasource.tsx
  packages/scenes-app/src/demos/groupByStatic.tsx
  packages/scenes-app/src/demos/index.ts
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/groupby/findActiveGroupByVariablesByUid.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: minor, release

#566 SceneGridLayout: Fixes missing resize handles
  packages/scenes-app/src/demos/grid.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: release

#569 Variable: Fixes performance issues with variables with many select options
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: patch, release

#571 GroupBy variable: Fix variable type
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
Labels: patch, release

#574 TextBoxVariable: Fixes url sync key when name changes
  packages/scenes/src/services/SceneObjectUrlSyncConfig.ts
  packages/scenes/src/variables/variants/TextBoxVariable.test.tsx
  packages/scenes/src/variables/variants/TextBoxVariable.tsx
Labels: patch, release

#579 ResizeHandle: New style
  packages/scenes-app/src/demos/grid.tsx
  packages/scenes/src/components/layout/grid/SceneGridLayoutRenderer.tsx
Labels: release

#583 GroupBy: Add variable type guard
  packages/scenes/src/index.ts
  packages/scenes/src/variables/variants/guards.ts
Labels: patch, release

#593 QueryController: Update global window query counter
  packages/scenes/src/behaviors/SceneQueryController.ts
Labels: minor, release

#596 SceneQueryRunner: Improved way to detect changes to adhoc filters and group by variables
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/variables/VariableDependencyConfig.ts
Labels: minor, release

#598 VariableDependencyConfig: do not scan state if `variableNames` is defined
  packages/scenes/src/variables/VariableDependencyConfig.test.ts
  packages/scenes/src/variables/VariableDependencyConfig.ts
Labels: patch, release

#595 Variables: Clear current value when no options are returned
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
  packages/scenes/src/variables/variants/MultiValueVariable.ts
Labels: minor, release

#599 VariableDependencyConfig: Support `*` to extract dependencies from every state path
  docusaurus/docs/advanced-variables.md
  packages/scenes/src/variables/VariableDependencyConfig.test.ts
  packages/scenes/src/variables/VariableDependencyConfig.ts
Labels: minor, release

#602 VizPanel: Fixes streaming issue
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: patch

#600 SceneQueryController: Fixes double complete counting
  packages/scenes/src/behaviors/SceneQueryController.test.ts
  packages/scenes/src/behaviors/SceneQueryController.ts
  packages/scenes/src/querying/registerQueryWithController.ts
Labels: patch, release

#603 SceneQueryRunner: Add query caching options
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: minor, release

#570 Update grafana peer dependencies
  packages/scenes-app/package.json
  packages/scenes/package.json
  packages/scenes/src/components/NestedScene.test.tsx
  packages/scenes/src/components/SceneApp/SceneApp.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/core/PanelBuilders/FieldConfigBuilders.ts
  packages/scenes/src/core/PanelBuilders/__snapshots__/VizPanelBuilder.test.ts.snap
  packages/scenes/src/core/PanelBuilders/index.ts
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/layers/SceneDataLayerControls.test.tsx
  packages/scenes/src/querying/layers/annotations/standardAnnotationsSupport.ts
  packages/scenes/src/utils/ControlsLabel.tsx
  packages/scenes/src/utils/LoadingIndicator.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/variants/query/utils.ts
  packages/scenes/utils/setupTests.ts
  yarn.lock
Labels: minor, release, dependencies

#609 VizPanel: Fixes issue with non memoizable PanelData
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: patch, release

#610 SceneObjectBase: Minor optimization to setParent
  packages/scenes/src/core/SceneObjectBase.tsx
Labels: minor

#611 VizPanel: Pass container width to data provider always
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
Labels: minor, release

#616 Legend sorting fix
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: patch, release

#617 Auto: Updating auto
  package.json
  yarn.lock
Labels: release

#614 AdHocFilters: Auto focus value when key is selected
  packages/scenes-app/src/demos/verticalControlsLayoutDemo.tsx
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
Labels: minor, release

#624 Group row title and actions together on the left side
  packages/scenes/src/components/layout/grid/SceneGridRow.tsx
Labels: patch, release
