Repository grafana/scenes, pull requests merged in 2025-07, with the labels that each got.

#1177 QueryVariable: Add ability to provide custom static options
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: release

#1166 AdHocFiltersCombobox: Update z-index
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
Labels: patch, release

#1191 Custom variable: support newline separated options
  packages/scenes/src/variables/variants/CustomVariable.test.ts
  packages/scenes/src/variables/variants/CustomVariable.tsx
Labels: patch, release

#1195 Enhance `SceneRenderProfiler` with additional interaction tracking
  packages/scenes/src/behaviors/SceneRenderProfiler.ts
  packages/scenes/src/behaviors/types.ts
  packages/scenes/src/components/SceneRefreshPicker.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/utils/getDataSource.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/variants/MultiValueVariable.ts
  packages/scenes/src/variables/variants/ScopesVariable.tsx
Labels: patch, release

#1198 Make `SceneRenderProfiler` optional and injectable
  packages/scenes/src/behaviors/SceneQueryController.ts
  packages/scenes/src/behaviors/SceneRenderProfiler.ts
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.tsx
  packages/scenes/src/utils/getDataSource.ts
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: patch, release, area/performance
