Repository grafana/scenes, pull requests merged in 2025-05, with the labels that each got.

#1118 AdHocVariable: Add more suggestive injected filters tooltips
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx
Labels: patch, release

#1113 SceneTimePicker: Add defaultQuickRanges to override the default time range options
  packages/scenes-app/package.json
  packages/scenes/src/behaviors/SceneRenderProfiler.ts
  packages/scenes/src/components/SceneTimePicker.test.tsx
  packages/scenes/src/components/SceneTimePicker.tsx
  yarn.lock
Labels: release

#1124 VizPanel: Cloning should ignore pluginInstanceState
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/core/sceneGraph/cloneSceneObject.test.ts
  packages/scenes/src/core/sceneGraph/cloneSceneObject.ts
  packages/scenes/src/core/sceneGraph/utils.ts
  packages/scenes/src/index.ts
Labels: minor, release

#1127 VizPanel: Allow passing partial state when cloning
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: patch, release, released

#1121 Scopes: Replace ScopesBridge with ScopesVariable
  packages/scenes-app/src/demos/index.ts
  packages/scenes-app/src/demos/scopesDemo.tsx
  packages/scenes/src/components/SceneApp/SceneApp.tsx
  packages/scenes/src/components/SceneApp/SceneAppPage.tsx
  packages/scenes/src/components/SceneApp/types.ts
  packages/scenes/src/core/SceneScopesBridge.ts
  packages/scenes/src/core/sceneGraph/index.ts
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/__snapshots__/SceneQueryRunner.test.ts.snap
  packages/scenes/src/variables/VariableDependencyConfig.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/components/VariableValueSelectors.tsx
  packages/scenes/src/variables/constants.ts
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
  packages/scenes/src/variables/types.ts
  packages/scenes/src/variables/variants/ScopesVariable.test.tsx
  packages/scenes/src/variables/variants/ScopesVariable.tsx
Labels: minor, release

#1122 GroupByVariable: Add support for default values
  CHANGELOG.md
  packages/scenes/CHANGELOG.md
  packages/scenes/src/variables/groupby/DefaultGroupByCustomIndicatorContainer.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/groupby/GroupByVariableUrlSyncHandler.ts
Labels: minor, release

#1130 ScopesVariable: Only emit value changed when value has changed
  packages/scenes/src/variables/variants/ScopesVariable.test.tsx
  packages/scenes/src/variables/variants/ScopesVariable.tsx
Labels: minor, release

#1139 AdHocFiltersVariableUrlSyncHandler: fix url state containing `#` char
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
Labels: type/bug, minor, release
