Repository grafana/scenes, pull requests merged in 2025-01, with the labels that each got.

#1015 QueryVariable: Use correct option property for variable options sorting
  packages/scenes/src/variables/variants/query/QueryVariable.test.tsx
  packages/scenes/src/variables/variants/query/utils.ts
Labels: type/bug, patch, release, area/variables

#1021 ScenesQueryRunner: Add minInterval to variable dependencies
  packages/scenes/src/querying/SceneQueryRunner.ts
Labels: patch, release, area/variables

#1024 sceneUtils: export methods for generating scenes URLs in external applications
  packages/scenes/src/index.ts
  packages/scenes/src/variables/utils.test.ts
  packages/scenes/src/variables/utils.ts
Labels: minor, release, no-changelog

#1029 AdHocFilterVariable: Force option label to be a string
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: patch, release, area/variables

#1028 Layouts: Add ability to hook into VizPanelRenderer events
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/core/types.ts
Labels: minor, release

#1034 AdHocFilters: allow setting filter meta in getTagKeysProvider
  packages/scenes/src/index.ts
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: minor, release, usecase/app-plugins

#1030 SceneVariableSet: Allow propagation of variable changes through local variable
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
Labels: minor, release

#1036 Combobox: Displaying value instead of valueLabels on edit
  CHANGELOG.md
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
Labels: type/bug, patch, release, area/variables

#1033 Fix issue with custom variables losing url value when there are no options
  packages/scenes/src/variables/variants/CustomVariable.tsx
Labels: minor, release
