Repository grafana/scenes, pull requests merged in 2025-02, with the labels that each got.

#1044 Variables: Prevent queries from runners which are not specific to the query runner datasource
  packages/scenes/src/variables/utils.test.ts
  packages/scenes/src/variables/utils.ts
Labels: patch, release

#1050 Themes: Fixes variable labels to support border radius
  packages/scenes/src/utils/ControlsLabel.tsx
  packages/scenes/src/variables/components/VariableValueSelectors.tsx
Labels: minor, release

#979 Update to `react-router@6`
  packages/scenes-app/.config/webpack/webpack.config.ts
  packages/scenes-app/package.json
  packages/scenes-app/src/components/App/App.tsx
  packages/scenes-app/src/components/Routes/Routes.tsx
  packages/scenes-app/src/demos/adhocFiltersDemo.tsx
  packages/scenes-app/src/demos/cursorSync.tsx
  packages/scenes-app/src/demos/docs-examples.tsx
  packages/scenes-app/src/demos/dynamicPage.tsx
  packages/scenes-app/src/demos/nestedVariables.tsx
  packages/scenes-app/src/demos/split.tsx
  packages/scenes-app/src/demos/urlSyncTest.tsx
  packages/scenes-app/src/demos/variables.tsx
  packages/scenes-app/src/demos/withDrilldown/WithDrilldown.tsx
  packages/scenes-app/src/home-demo/HomeApp.tsx
  packages/scenes-app/src/monitoring-app/GrafanaMonitoringApp.tsx
  packages/scenes-app/src/pages/DemoListPage.tsx
  packages/scenes-app/src/react-demo/DrilldownDemoPage.tsx
  packages/scenes-app/src/react-demo/Home.tsx
  packages/scenes-react/package.json
  packages/scenes-react/src/contexts/SceneContextProvider.test.tsx
  packages/scenes/jest.config.ts
  packages/scenes/package.json
  packages/scenes/src/components/SceneApp/SceneApp.test.tsx
  packages/scenes/src/components/SceneApp/SceneApp.tsx
  packages/scenes/src/components/SceneApp/SceneAppPage.test.tsx
  packages/scenes/src/components/SceneApp/SceneAppPage.tsx
  packages/scenes/src/components/SceneApp/SceneAppPageView.tsx
  packages/scenes/src/components/SceneApp/types.ts
  packages/scenes/src/components/SceneApp/utils.ts
  packages/scenes/src/utils/utils.ts
  packages/scenes/utils/setupTests.ts
  packages/scenes/utils/setupTestsAfterEnv.ts
  packages/scenes/utils/test/TestContextProvider.tsx
  packages/scenes/utils/test/index.ts
  packages/scenes/utils/test/renderAppInsideRoutingWithStartingUrl.tsx
  packages/scenes/utils/test/updateUrlStateAndSyncState.tsx
  packages/scenes/utils/test/utils.tsx
  yarn.lock
Labels: major, release, dependencies

#1053 Fix the `getLegacyPanelId` method in `VizPanel`
  packages/scenes/src/components/VizPanel/VizPanel.test.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
Labels: patch, release

#1059 SceneGridLayout: Allow to hook into `onDragStart` event
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
  packages/scenes/src/components/layout/grid/types.ts
  packages/scenes/src/index.ts
Labels: patch, release

#967 Utils: Spread objects in cloneSceneObjectState
  packages/scenes/src/core/sceneGraph/utils.ts
  packages/scenes/src/querying/SceneDataTransformer.test.ts
Labels: type/bug, patch, release

#1063 Profiling: explicitly set profiling names
  packages/scenes/src/behaviors/SceneQueryController.ts
  packages/scenes/src/behaviors/types.ts
  packages/scenes/src/components/SceneRefreshPicker.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
Labels: release
