Repository grafana/scenes, pull requests merged in 2025-09, with the labels that each got.

#1243 SceneGridLayout: Adjust item y position for all children after a breakpoint
  packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
Labels: release

#1248 SceneTimePicker: Pass move duration tooltip
  packages/scenes/src/components/SceneTimePicker.tsx
  packages/scenes/src/locales/en-US/grafana-scenes.json
Labels: minor, release

#1240 SceneInteractionProfiler: Measure atomic selectbox interactions on adhocs and groupBy
  packages/scenes/src/behaviors/SceneInteractionTracker.ts
  packages/scenes/src/behaviors/SceneRenderProfiler.test.ts
  packages/scenes/src/behaviors/SceneRenderProfiler.ts
  packages/scenes/src/behaviors/index.ts
  packages/scenes/src/behaviors/types.ts
  packages/scenes/src/core/sceneGraph/getInteractionTracker.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
Labels: minor, release

#1250 AdHocVariables: Show custom value first for `=~` and `!~` regex operators
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
Labels: type/bug, minor, release, area/variables
