Repository grafana/scenes, pull requests merged in 2025-04, with the labels that each got.

#1077 Bump rollup and related deps
  packages/scenes-react/package.json
  packages/scenes-react/rollup.config.ts
  packages/scenes/package.json
  packages/scenes/rollup.config.ts
  yarn.lock
Labels: patch, release, dependencies

#1087 GroupByVariable: Add browser history action support for GroupBy var
  packages/scenes/src/variables/groupby/GroupByVariable.test.tsx
  packages/scenes/src/variables/groupby/GroupByVariableUrlSyncHandler.ts
  packages/scenes/src/variables/variants/MultiValueVariable.test.ts
Labels: patch, release

#1091 VariableControl: Add props needed in core dashboards
  packages/scenes/src/utils/ControlsLabel.tsx
Labels: minor, release

#1094 ConstantVariable: Support interpolation and dependency of other variables in constant value
  packages/scenes/src/variables/variants/ConstantVariable.test.ts
  packages/scenes/src/variables/variants/ConstantVariable.ts
Labels: minor, release

#1096 Variables: Switch between multi and single select if state changes
  packages/scenes/src/index.ts
  packages/scenes/src/variables/components/VariableValueSelect.test.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/variants/CustomVariable.tsx
  packages/scenes/src/variables/variants/DataSourceVariable.tsx
  packages/scenes/src/variables/variants/TestVariable.tsx
  packages/scenes/src/variables/variants/query/QueryVariable.tsx
Labels: minor, release

#1097 Variables: Rename renderSelectForVariable to MultiOrSingleValueSelect
  packages/scenes/src/index.ts
Labels: patch, release

#1104 Variables: Notify scene objects in depth order
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/variables/TestScene.ts
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
  packages/scenes/src/variables/sets/SceneVariableSet.ts
Labels: release

#1095 AdHocFilters: Dashboard level filters
  packages/scenes-app/src/demos/adhocFiltersDemo.tsx
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
  packages/scenes/src/variables/adhoc/getAdHocFiltersFromScopes.test.ts
  packages/scenes/src/variables/adhoc/getAdHocFiltersFromScopes.ts
Labels: minor, release

#1109 Validate timezone
  packages/scenes/src/core/SceneTimeRange.test.tsx
  packages/scenes/src/core/SceneTimeRange.tsx
Labels: patch, release
