Repository grafana/scenes, pull requests merged in 2025-06, with the labels that each got.

#1136 ScopesVariable: Emit value changed when there no scopes selected
  packages/scenes/src/variables/variants/ScopesVariable.test.tsx
  packages/scenes/src/variables/variants/ScopesVariable.tsx
Labels: minor, release

#1140 VariableDependencyConfig: Fix test
  packages/scenes/src/variables/VariableDependencyConfig.test.ts
Labels: patch, release, no-changelog

#1144 Scopes: Add annotation query support
  packages/scenes/src/querying/layers/annotations/AnnotationsDataLayer.test.ts
  packages/scenes/src/querying/layers/annotations/standardAnnotationQuery.ts
Labels: minor, release

#1132 AdHocVariable: Refactor origin filters
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/__snapshots__/SceneQueryRunner.test.ts.snap
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersComboboxRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts
  packages/scenes/src/variables/utils.ts
Labels: minor, release

#1151 Internationalisation: Add markup for translations
  crowdin.yml
  package.json
  packages/scenes-app/tsconfig.json
  packages/scenes-react/tsconfig.json
  packages/scenes/eslint.config.js
  packages/scenes/package.json
  packages/scenes/rollup.config.ts
  packages/scenes/src/components/NestedScene.tsx
  packages/scenes/src/components/SceneApp/SceneAppPage.tsx
  packages/scenes/src/components/SceneDebugger/SceneDebugger.tsx
  packages/scenes/src/components/SceneTimeRangeCompare.tsx
  packages/scenes/src/components/VizPanel/VizPanel.tsx
  packages/scenes/src/components/VizPanel/VizPanelExploreButton.tsx
  packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
  packages/scenes/src/components/VizPanel/VizPanelSeriesLimit.tsx
  packages/scenes/src/components/layout/grid/SceneGridRow.tsx
  packages/scenes/src/components/layout/split/Splitter.tsx
  packages/scenes/src/index.ts
  packages/scenes/src/locales/en-US/grafana-scenes.json
  packages/scenes/src/locales/i18next-parser.config.cjs
  packages/scenes/src/utils/ControlsLabel.tsx
  packages/scenes/src/utils/LoadingIndicator.tsx
  packages/scenes/src/utils/loadResources.ts
  packages/scenes/src/variables/TestScene.ts
  packages/scenes/src/variables/adhoc/AdHocFilterBuilder.tsx
  packages/scenes/src/variables/adhoc/AdHocFilterRenderer.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFilterPill.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/DropdownItem.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/MultiValuePill.tsx
  packages/scenes/src/variables/components/VariableValueInput.tsx
  packages/scenes/src/variables/components/VariableValueSelect.tsx
  packages/scenes/src/variables/groupby/DefaultGroupByCustomIndicatorContainer.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
  packages/scenes/src/variables/interpolation/formatRegistry.ts
  packages/scenes/src/variables/variants/DataSourceVariable.tsx
  packages/scenes/src/variables/variants/IntervalVariable.tsx
  packages/scenes/src/variables/variants/TestVariable.tsx
  packages/scenes/tsconfig.json
  yarn.lock
Labels: minor, release

#1162 i18n: fixes peer dependencies
  packages/scenes/package.json
  yarn.lock
Labels: patch, release

#1155 SceneQueryRunner: Detect local variable change
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/__snapshots__/SceneQueryRunner.test.ts.snap
  packages/scenes/src/variables/sets/SceneVariableSet.test.tsx
Labels: minor, release

#1165 sceneGraph: findObject should return first match
  packages/scenes/src/core/SceneObjectBase.tsx
  packages/scenes/src/core/sceneGraph/sceneGraph.test.tsx
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
  packages/scenes/src/core/types.ts
Labels: minor, release

#1157 SceneTimeRangeCompare: Add option to hide checkbox
  packages/scenes/jest.config.ts
  packages/scenes/src/components/SceneTimeRangeCompare.test.tsx
  packages/scenes/src/components/SceneTimeRangeCompare.tsx
Labels: release
