Repository grafana/scenes, pull requests merged in 2025-03, with the labels that each got.

#1070 SceneObjectBase: Fixes crash TypeError circular reference when stringifying scene object
  packages/scenes/src/core/SceneObjectBase.test.ts
  packages/scenes/src/core/SceneObjectBase.tsx
Labels: minor, release

#1071 Variables: Unify options filtering to use most up to date implementation
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/AdHocFiltersCombobox.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersCombobox/utils.ts
  packages/scenes/src/variables/adhoc/getAdhocOptionSearcher.ts
  packages/scenes/src/variables/components/getOptionSearcher.ts
  packages/scenes/src/variables/filter.test.ts
  packages/scenes/src/variables/filter.ts
  packages/scenes/src/variables/utils.test.ts
  packages/scenes/src/variables/utils.ts
Labels: patch, release, area/variables

#990 Scopes: Add `ScopesBridge` object
  packages/scenes/src/components/SceneApp/SceneApp.tsx
  packages/scenes/src/components/SceneApp/SceneAppPage.tsx
  packages/scenes/src/components/SceneApp/types.ts
  packages/scenes/src/core/SceneScopesBridge.ts
  packages/scenes/src/core/sceneGraph/index.ts
  packages/scenes/src/core/sceneGraph/sceneGraph.ts
  packages/scenes/src/index.ts
  packages/scenes/src/querying/SceneQueryRunner.test.ts
  packages/scenes/src/querying/SceneQueryRunner.ts
  packages/scenes/src/querying/__snapshots__/SceneQueryRunner.test.ts.snap
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/groupby/GroupByVariable.tsx
Labels: patch, release

#1074 fix: explore button to preserve datasource selection in mixed datasource panels
  packages/scenes/src/components/VizPanel/VizPanelExploreButton.tsx
  packages/scenes/src/utils/explore.test.ts
  packages/scenes/src/utils/explore.ts
Labels: minor, release

#1073 AdhocVariable: Inject scopes in baseFilters
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
  packages/scenes/src/variables/adhoc/getAdHocFiltersFromScopes.test.ts
  packages/scenes/src/variables/adhoc/getAdHocFiltersFromScopes.ts
Labels: patch, release

#1078 AdHocFilters: Fix removing all scopes and cleaning up the adhoc
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.test.tsx
  packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx
Labels: patch, release

#1076 Local dev: link to all @grafana modules in core
  packages/scenes/package.json
  scripts/dev.sh
  yarn.lock
Labels: dependencies, no-changelog
